---
- hosts: [us-west]
  remote_user: ubuntu
  tasks:
    - name: Update the base Unbutu image
      apt: update_cache=yes
      become: yes
      become_method: sudo

    - name: Install build dependencies
      apt: name={{ item }} state=latest update_cache=yes
      become: yes
      become_method: sudo
      with_items:
        - python-dev
        - python3-venv
        - python3-pip
        - build-essential
        - postgresql-client
        - nginx
    - name: register imager here
      stat: path=/home/ubuntu/django-imager
      register: repo_stat

    - name: clone repo
      command: git clone https://github.com/jayadams011/django-imager.git
      when: not repo_stat.stat.exists

    - name: migrate database
      command: python3 django-imager/imagersite/manage.py/migrate
      
    
    # Don't forget to collectstatic and migrate if necessary

    - name: Create a virtual env for the project to run in
      command: python3 -m venv /home/ubuntu/ENV
      # become: yes
      # become_method: sudo

    - name: Install Gunicorn into Virtual Environment
      pip: virtualenv=/home/ubuntu/ENV name=gunicorn
      # become: yes
      # become_method: sudo

    - name: Register the backup default config for nginx
      stat: path=/etc/nginx/sites-available/default.bak
      register: default_stat

    - name: mv and rename default nginx config
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
      become: yes
      become_method: sudo
      when: not default_stat.stat.exists

    - name: Create a new Nginx config
      template:
        src: templates/nginx_config
        dest: /etc/nginx/sites-available/default
      become: yes
      become_method: sudo

    - name: Register the backup default config for gunicorn
      stat: path=/etc/systemd/system/gunicorn.service.bak
      register: gunicorn_stat

    - name: mv and rename default gunicorn config
      command: mv /etc/systemd/system/gunicorn.service /etc/systemd/system/gunicorn.service.bak
      become: yes
      become_method: sudo
      when: not gunicorn_stat.stat.exists

    - name: Create a new gunicorn config
      template:
        src: templates/gunicorn_config
        dest: /etc/systemd/system/gunicorn.service
      become: yes
      become_method: sudo


    # Don't forget to start/restart your services
    - name: Enable gunicorn config
      command: systemctl enable gunicorn
      become: yes
      become_method: sudo

    - name: Start gunicorn config
      command: systemctl start gunicorn
      become: yes
      become_method: sudo

    - name: Restart gunicorn config
      command: systemctl restart gunicorn
      become: yes
      become_method: sudo

    - name: Enable nginx config
      command: systemctl enable nginx
      become: yes
      become_method: sudo

    - name: Start nginx config
      command: systemctl start nginx
      become: yes
      become_method: sudo

    - name: Restart nginx config
      command: systemctl restart nginx
      become: yes
      become_method: sudo
